# **Importing the Libraries**


In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# **Importing the dataset**

In [3]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [5]:
dataset = pd.read_csv('/content/gdrive/My Drive/datasets/Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [12]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

# Taking care of missing data

In [19]:
# Inorder to handle missing data we use, SimpleImputer to replace the missing values


from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean")
X[:,1:3] = imputer.fit_transform(X[:, 1:3])
X


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Encoding categorical data

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(), [0])], remainder = 'passthrough')

X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)



# Encoding dependent Variable



In [27]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
y= labelencoder.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Feature Scaling

In [30]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)
X

array([[ 1.22474487e+00, -1.22474487e+00,  1.22474487e+00,
        -6.54653671e-01, -6.54653671e-01,  7.58874362e-01,
         7.49473254e-01],
       [-8.16496581e-01,  8.16496581e-01, -8.16496581e-01,
        -6.54653671e-01,  1.52752523e+00, -1.71150388e+00,
        -1.43817841e+00],
       [-8.16496581e-01,  8.16496581e-01, -8.16496581e-01,
         1.52752523e+00, -6.54653671e-01, -1.27555478e+00,
        -8.91265492e-01],
       [-8.16496581e-01,  8.16496581e-01, -8.16496581e-01,
        -6.54653671e-01,  1.52752523e+00, -1.13023841e-01,
        -2.53200424e-01],
       [-8.16496581e-01,  8.16496581e-01, -8.16496581e-01,
         1.52752523e+00, -6.54653671e-01,  1.77608893e-01,
         2.35783334e-16],
       [ 1.22474487e+00, -1.22474487e+00,  1.22474487e+00,
        -6.54653671e-01, -6.54653671e-01, -5.48972942e-01,
        -5.26656882e-01],
       [-8.16496581e-01,  8.16496581e-01, -8.16496581e-01,
        -6.54653671e-01,  1.52752523e+00,  8.88178420e-17,
        -1.0735698

# Splitting the dataset

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)